log_level: INFO  # Log level (string)
samples_file: ~ # Path YAML file with samples - eg [{id: ID, files: [F1, F2]}, ...] (path)
tag: ~ # Tag identifying the pipeline run (defaults to a timestamp - YYMMDDHHMMSS) (string)
resultdir: ~ # Results base directory where output files are copied (path)
workdir: ~ # Working directory where intermediate files are stored (path)
logdir: ~ # Log directory (path)
config_file: ~ # Path to config file (path)
executor:
  name: subprocess  # Name of the executor to use (string)
  memory: 2 GiB # Ammount of memory to allocate to jobs started (if supported by the executor) (size)
  cpus: 1 # Number of CPUs to allocate to jobs started (if supported by the executor) (integer)
mail:
  send: false  # Send mail (boolean)
  cc_addr: ~ # Default list of CC recipients (array)
  to_addr: ~ # Default list of recipients (array)
  from_addr: ~ # Default from address (string)
  start:
    subject: '{{ analysis }} started'  # Subject of the mail (jinja2 template) (string)
    body: "{{ analysis }} has started for {{ samples.unique_ids|length }} sample(s).\n
      \nThe following samples are being analyzed:\n{% for id in samples.unique_ids
      %}\n{{ id }}\n{%- endfor %}\n" # Body of the mail (jinja2 template) (string)
  end:
    subject: '{{ analysis }} finished'  # Subject of the mail (jinja2 template) (string)
    body: "{{ analysis }} has finished processing {{ samples.unique_ids|length }}
      sample(s).\n{% if samples.failed|length > 0 %}\n❗️ Analysis failed for the following
      samples:\n{% for id in samples.failed.unique_ids %}\n{{ id }}\n{%- endfor %}\n
      {% endif %}\n{%- if samples.complete|length > 0 %}\n✅ Analysis completed successfully
      for the following samples:\n{% for id in samples.complete.unique_ids %}\n{{
      id }}\n{%- endfor %}\n{% endif %}\n" # Body of the mail (jinja2 template) (string)
  smtp:
    host: ~  # SMTP host (string)
    password: ~ # SMTP password (string)
    user: ~ # SMTP username (string)
    tls: false # Use TLS (boolean)
    port: 25 # SMTP port (integer)
rsync:
  overwrite: false  # Overwrite existing results (boolean)
  large_file_threshold: 100M # Files larger than this will be copied in a separate job (eg. 100M, 1 GB) (string)
nextflow:
  threads: 2  # Threads for nextflow manager (integer)
  env: # Environment variables that will be passed to the nextflow process (mapping)
  - ''
  java_module: java # Java module (string)
  nf_module: nextflow # Nextflow module (string)
  ansi_log: false # Enable ANSI log (boolean)
  profile: ~ # Nextflow profile (string)
  config: ~ # Nextflow config file (path)
grid_engine:
  queue: all.q  # Grid Engine queue (string)
  pe: mpi # Grid Engine parallel environment (string)
unpack:
  init: ~  # Code to run before unpacking (Bash) (string)
  timeout: 60 # Timeout (in seconds) to wait for unpacked file to become available (integer)
  threads: 40 # Threads for decompression (integer)
  exit: ~ # Code to run after unpacking (Bash) (string)
