log_level: INFO  # Log level (string)
samples_file: ~ # Path YAML file with samples - eg [{id: ID, files: [F1, F2]}, ...] (path)
tag: ~ # Tag identifying the pipeline run (defaults to a timestamp - YYMMDDHHMMSS) (string)
resultdir: ~ # Results base directory where output files are copied (path)
workdir: ~ # Working directory where intermediate files are stored (path)
logdir: ~ # Log directory (path)
config_file: ~ # Path to config file (path)
executor:
  name: subprocess  # Name of the executor to use (string)
  memory: 2 GiB # Ammount of memory to allocate to jobs started (if supported by the executor) (size)
  cpus: 1 # Number of CPUs to allocate to jobs started (if supported by the executor) (integer)
rsync:
  overwrite: false  # Overwrite existing results (boolean)
  large_file_threshold: 100M # Files larger than this will be copied in a separate job (eg. 100M, 1 GB) (string)
nextflow:
  threads: 2  # Threads for nextflow manager (integer)
  env: # Environment variables that will be passed to the nextflow process (mapping)
  - ''
  java_module: java # Java module (string)
  nf_module: nextflow # Nextflow module (string)
  ansi_log: false # Enable ANSI log (boolean)
  profile: ~ # Nextflow profile (string)
  config: ~ # Nextflow config file (path)
