log_level: INFO  # Log level (string)
copy_skipped: false # Copy skipped runner output (boolean)
merge: false # Merge samples with same ID (boolean)
read_length: 150 # Sample read length (integer)
strandedness: unstranded # Strandedness of RNA-seq library (string)
samples_file: ~ # Path YAML file with samples - eg [{id: ID, files: [F1, F2]}, ...] (path)
tag: ~ # Tag identifying the pipeline run (defaults to a timestamp - YYMMDDHHMMSS) (string)
resultdir: ~ # Results base directory where output files are copied (path)
workdir: ~ # Working directory where intermediate files are stored (path)
logdir: ~ # Log directory (path)
config_file: ~ # Path to config file (path)
executor:
  name: subprocess  # Name of the executor to use (string)
  memory: 2 GiB # Ammount of memory to allocate to jobs started (if supported by the executor) (size)
  cpus: 1 # Number of CPUs to allocate to jobs started (if supported by the executor) (integer)
rnaseq:
  skip: false  # Skip nf-core/rnaseq (boolean)
  aligner: ~ # RNA-seq aligner (string)
  rsem_index: ~ # Path to RSEM genome index (path)
  star_index: ~ # Path to STAR genome index (path)
  gene_bed: ~ # Path to genome gene bed file (path)
  gtf: ~ # Path to genome gtf file (path)
  fasta: ~ # Path to genome fasta file (path)
  genome: ~ # Genome reference (string)
  nf_main: ~ # Path to nf-core/rnaseq main.nf (path)
  force: false # Overwrite any existing output (boolean)
rnafusion:
  skip: false  # Skip nf-core/rnafusion (boolean)
  fusionreport_tool_cutoff: 1 # Minimum number of callers for fusion to be reported (integer)
  arriba_protein_domain: ~ # Path to arriba protein domains file (path)
  arriba_blacklist: ~ # Path to arriba blacklist file (path)
  arriba_ref: ~ # Path to arriba references (path)
  genomes_base: ~ # Path to rnafusion references (path)
  nf_main: ~ # Path to nf-core/rnafusion main.nf (path)
  force: false # Overwrite any existing output (boolean)
qlucore:
  skip: false  # Skip qlucore mapping (boolean)
  subsample_frac: 0.2 # Fraction of reads to subsample (number)
  subsample_threads: 12 # Number of threads to use for subsampling (integer)
  starfusion_ref: ~ # Path to STAR-Fusion reference (path)
  nf_main: ~ # Path to nf-core/rnafusion main.nf (path)
  subsample_init: '' # Code to run before qlucore subsampling (string)
  force: false # Overwrite any existing output (boolean)
mail:
  send: false  # Send mail (boolean)
  cc_addr: ~ # Default list of CC recipients (array)
  to_addr: ~ # Default list of recipients (array)
  from_addr: ~ # Default from address (string)
  start:
    subject: '{{ analysis }} started'  # Subject of the mail (jinja2 template) (string)
    body: "{{ analysis }} has started for {{ samples.unique_ids|length }} sample(s).\n
      \nThe following samples are being analyzed:\n{% for id in samples.unique_ids
      %}\n{{ id }}\n{%- endfor %}\n" # Body of the mail (jinja2 template) (string)
  end:
    subject: '{{ analysis }} finished'  # Subject of the mail (jinja2 template) (string)
    body: "{{ analysis }} has finished processing {{ samples.unique_ids|length }}
      sample(s).\n{% if samples.failed|length > 0 %}\n❗️ Analysis failed for the following
      samples:\n{% for id in samples.failed.unique_ids %}\n{{ id }}\n{%- endfor %}\n
      {% endif %}\n{%- if samples.complete|length > 0 %}\n✅ Analysis completed successfully
      for the following samples:\n{% for id in samples.complete.unique_ids %}\n{{
      id }}\n{%- endfor %}\n{% endif %}\n" # Body of the mail (jinja2 template) (string)
  smtp:
    host: ~  # SMTP host (string)
    password: ~ # SMTP password (string)
    user: ~ # SMTP username (string)
    tls: false # Use TLS (boolean)
    port: 25 # SMTP port (integer)
rsync:
  overwrite: false  # Overwrite existing results (boolean)
  large_file_threshold: 100M # Files larger than this will be copied in a separate job (eg. 100M, 1 GB) (string)
nextflow:
  threads: 2  # Threads for nextflow manager (integer)
  env: # Environment variables that will be passed to the nextflow process (mapping)
  - ''
  java_module: java # Java module (string)
  nf_module: nextflow # Nextflow module (string)
  ansi_log: false # Enable ANSI log (boolean)
  profile: ~ # Nextflow profile (string)
  config: ~ # Nextflow config file (path)
hcp:
  credentials: ~  # IRIS credentials file (path)
  parallel: 4 # Number of parallel HCP conenctions (integer)
  fastq_temp: ~ # Temporary directory for fastq files (path)
slims:
  url: ~  # SLIMS URL (string)
  novel_max_age: 1 year # Maximum age of novel samples (eg. "7 days", "1 month", "1 year") (string)
  dry_run: false # Do not create SLIMS bioinformatics objects (boolean)
  unrestrict_parents: false # Allow parent records to have different IDs than the child records (boolean)
  allow_duplicates: false # Allow duplicate samples (eg. if a pre-hook can handle this) (boolean)
  id: ~ # Manually select SLIMS Sample ID(s) (array)
  check_criteria: ~ # SLIMS criteria for checking completed records (eg. "cntn_cstm_SecondaryAnalysis equals 1337") (string)
  find_criteria: ~ # SLIMS criteria for finding records (eg. "cntn_cstm_SecondaryAnalysis equals 1337") (string)
  derive: ~ # Mapping for creating derived records in SLIMS (Use curly braces to access keys in the samples object) (array)
  map: ~ # Mapping of keys to SLIMS field(s) (Use json: prefix and dot notation for JSON fields) (mapping)
  password: ~ # SLIMS password (string)
  username: ~ # SLIMS username (string)
grid_engine:
  queue: all.q  # Grid Engine queue (string)
  pe: mpi # Grid Engine parallel environment (string)
unpack:
  init: ~  # Code to run before unpacking (Bash) (string)
  timeout: 60 # Timeout (in seconds) to wait for unpacked file to become available (integer)
  threads: 40 # Threads for decompression (integer)
  exit: ~ # Code to run after unpacking (Bash) (string)
