[tool.poetry]
name = "cellophane"
version = "0.0.1"
description = "Library for wrappers integrating with SLIMS"
authors = ["Erik Demitz-Helin <erik.demitz-helin@gu.se>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
slims-python-api = "^6.8.0"
click = "^8.1.3"
psutil = "^5.9.4"
rich-click = "^1.6.0"
drmaa = "^0.7.9"
humanfriendly = "^10.0"
jsonschema = "^4.17.3"
ngpiris = "^4.2.0"


[tool.poetry.group.dev.dependencies]
pylint = "^2.15.10"
mypy = "^0.991"
bandit = "^1.7.4"
types-pyyaml = "^6.0.12.2"
black = "^22.12.0"
pyright = "^1.1.288"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
