type: object
properties:
  slims:
    type: object
    allOf:
      - required:
        - username
        - password
        - url
        - find_criteria
      - if: {properties: {check: {const: true}}}
        then:
          required:
            - check_criteria

    properties:
      url:
        description: SLIMS URL
        type: string

      username:
        description: SLIMS username
        type: string

      password:
        description: SLIMS password
        type: string
        secret: true

      map:
        description: "Mapping of keys to SLIMS field(s) (Use json: prefix and dot notation for JSON fields)"
        type: mapping
      
      derive:
        description: "Mapping for creating derived records in SLIMS (Use curly braces to access keys in the samples object)"
        type: mapping

      find_criteria:
        description: SLIMS criteria for finding records (eg. "cntn_cstm_SecondaryAnalysis equals 1337")
        type: string
      
      check_criteria:
        description: SLIMS criteria for checking completed records (eg. "cntn_cstm_SecondaryAnalysis equals 1337")
        type: string

      check:
        description: Check state of samples
        type: boolean
        default: true

      id:
        description: Manually select SLIMS Sample ID(s)
        type: array

      allow_duplicates:
        description: Allow duplicate samples (eg. if a pre-hook can handle this)
        default: false
        type: boolean

      unrestrict_parents:
        description: Allow parent records to have different IDs than the child records
        default: false
        type: boolean

      dry_run:
        description: Do not create SLIMS bioinformatics objects
        default: false
        type: boolean

      novel_max_age:
        description: Maximum age of novel samples (eg. "7 days", "1 month", "1 year")
        default: 1 year
        type: string