type: object
properties:
  slims:
    type: object
    required:
      - username
      - password
      - url
      - content_type
      - criteria
    properties:
      url:
        description: SLIMS URL
        type: string

      username:
        description: SLIMS username
        type: string

      password:
        description: SLIMS password
        type: string
        secret: true
      
      content_type:
        description: Content type PK for sample records
        type: integer

      criteria:
        description: SLIMS criteria for finding records (eg. "cntn_cstm_SecondaryAnalysis equals 1337")
        type: string

      map_field:
        description: "Mapping of keys to SLIMS field(s) (Use json: prefix and dot notation for JSON fields)"
        type: mapping

      derived_from:
        type: object
        required:
          - content_type
          - criteria
        criteria:
          description: SLIMS criteria for finding parent samples (see slims_criteria)
          type: string
        content_type:
          description: Content type PK for parent records
          type: integer


      bioinfo:
        type: object
        allOf:
        - if:
            anyOf:
              - properties: {check: {const: true}}
              - properties: {create: {const: true}}
          then:
            required:
              - content_type
              - state_field  
        - if:
            properties: {check: {const: true}}
          then:
            required:
              - check_criteria

        properties:
          content_type:
            description: Content type PK for bioinformatics records
            type: integer

          state_field:
            description: "Field with state of bioinformatics objects (Use json: prefix and dot notation for JSON fields)"
            type: string

          create:
            description: Create bioinformatics objects
            default: true
            type: boolean

          check:
            description: Check state of existing bioinformatics records
            type: boolean
            default: false

          check_criteria:
            description: Criteria for checking completed bioinformatics (see slims_criteria)
            type: string
            default: ""

      id:
        description: Manually select SLIMS Sample ID(s)
        type: array

      allow_duplicates:
        description: Allow duplicate samples (eg. if a pre-hook can handle this)
        default: false
        type: boolean

      dry_run:
        description: Do not create SLIMS bioinformatics objects
        default: false
        type: boolean

      novel_max_age:
        description: Maximum age of novel samples (eg. "7 days", "1 month", "1 year")
        default: 1 year
        type: string