type: object
properties:
  modules_init:
    type: path
    description: Path to modules init script

  petagene:
    type: object
    properties:
      sge_queue:
        type: string
        description: SGE queue for petasuite
      sge_pe:
        type: string
        description: SGE parallel environment for petasuite
      sge_slots:
        type: integer
        description: SGE slots (threads) for petasuite
        default: 40
      parallel:
        type: integer
        description: Maximum number of petasuite jobs to submit at once
        default: 100
    required:
      - sge_queue
      - sge_pe
      - sge_slots
