required:
  - rnaseq
  - rnafusion
  - qlucore

properties:
  strandedness:
    type: string
    description: Strandedness of RNA-seq library
    enum:
      - unstranded
      - forward
      - reverse
    default: unstranded

  limitSjdbInsertNsj:
    type: integer
    description: Maximum number of junctions to insert for STAR
    default: 1000000

  read_length:
    type: integer
    description: Sample read length
    default: 150

  merge:
    type: boolean
    description: Merge samples with same ID
    default: false

  copy_skipped:
    type: boolean
    description: Copy skipped runner output
    default: false

  rnaseq:
    type: object
    oneOf:
    - properties: {skip: {const: true}}
    - allOf:
      - required: [aligner]
      - oneOf:
        - required: [star_index]
        - required: [rsem_index]
      - oneOf:
        - required: [genome]
        - required: [fasta, gtf, gene_bed]

    properties:
      skip:
        type: boolean
        default: false
        description: Skip nf-core/rnaseq

      force:
        type: boolean
        default: false
        description: Overwrite any existing output

      nf_tag:
        type: string
        description: Tag to use for nf-core/rnaseq
        default: "3.14.0"

      nf_url:
        type: string
        description: URL to use for nf-core/rnaseq
        default: "https://github.com/nf-core/rnaseq"

      genome:
        type: string
        description: Genome reference

      fasta:
        type: path
        description: Path to genome fasta file

      transcript_fasta:
        type: path
        description: Path to transcriptome fasta file

      gtf:
        type: path
        description: Path to genome gtf file

      gene_bed:
        type: path
        description: Path to genome gene bed file

      star_index:
        type: path
        description: Path to STAR genome index

      salmon_index:
        type: path
        description: Path to Salmon genome index

      rsem_index:
        type: path
        description: Path to RSEM genome index

      aligner:
        type: string
        description: RNA-seq aligner
        enum:
          - star_salmon
          - star_rsem

  rnafusion:
    type: object
    oneOf:
    - properties: {skip: {const: true}}
    - required: [genomes_base, arriba_blacklist, arriba_protein_domain]
    properties:
      skip:
        type: boolean
        description: Skip nf-core/rnafusion
        default: false

      force:
        type: boolean
        description: Overwrite any existing output
        default: false

      nf_tag:
        type: string
        description: Tag to use for nf-core/rnafusion
        default: "3.0.1"

      nf_url:
        type: string
        description: URL to use for nf-core/rnafusion
        default: "https://github.com/nf-core/rnafusion"

      genomes_base:
        type: path
        description: Path to rnafusion references

      tools_cutoff:
        type: integer
        description: Minimum number of callers for fusion to be reported
        default: 1

  qlucore:
    type: object
    oneOf:
    - properties: {skip: {const: true}}
    - required: [starfusion_ref]
    properties:
      skip:
        type: boolean
        default: false
        description: Skip qlucore mapping

      force:
        type: boolean
        default: false
        description: Overwrite any existing output

      subsample_init:
        type: string
        description: Code to run before qlucore subsampling
        default: ""

      starfusion_ref:
        type: path
        description: Path to STAR-Fusion reference

      subsample_threads:
        type: integer
        description: Number of threads to use for subsampling
        default: 12

      subsample_frac:
        type: number
        description: Fraction of reads to subsample
        default: 0.2