type: object
properties:
  mail:
    type: object
    if: {properties: {skip: {const: false}}}
    then:
      required:
        - start
        - end
        - smtp
    properties:
      skip:
        type: boolean
        default: false
        description: "Don't send mail"
      start:
        type: object
        required:
          - subject
          - body
          - from_addr
          - to_addr
        properties: &message
          subject:
            type: string
            description: "Subject of the mail (jinja2 template)"
            default: "{{ analysis }} started"
          body:
            type: string
            description: "Body of the mail (jinja2 template)"
            default: |
              {{ analysis }} has started for {{ len(samples.unique_ids) }} sample(s).
              
              The following samples are being analyzed:
              {{ samples.unique_ids }}
          from_addr:
            type: string
            description: "From address to use"
          to_addr:
            type: array
            description: "List of recipients"
          cc_addr:
            type: array
            description: "List of CC recipients" 
      end:
        type: object
        required:
          - subject
          - body
          - from_addr
          - to_addr
        properties:
          <<: *message
          subject:
            type: string
            description: "Subject of the mail (jinja2 template)"
            default: "{{ analysis }} finished"
          body:
            type: string
            description: "Body of the mail (jinja2 template)"
            default: |
              {{ analysis }} has finished processing {{ len(samples) }} sample(s).

              {% if len(samples.failed) > 0 %}
              Analysis completed successfully for the following samples:
              {% for id in samples.failed.unique_ids %}
              {{ id }}
              {% endfor %}
              {% endif %}

              {% if len(samples.complete) > 0 %}
              Analysis completed with warnings for the following samples:
              {% for id in samples.complete.unique_ids %}
              {{ id }}
              {% endfor %}
              {% endif %}
      smtp:
        type: object
        required:
          - host
        properties:
          host:
            type: string
            description: "SMTP host"
          port:
            type: integer
            description: "SMTP port"
            default: 25
          tls:
            type: boolean
            description: "Use TLS"
            default: false
          user:
            type: string
            description: "SMTP username"
          password:
            type: string
            description: "SMTP password"
            secret: true

    