type: object
properties:
  mail:
    type: object
    if: {properties: {send: {const: true}}}
    then: {required: [smtp, from_addr, to_addr]}
    properties:
      send:
        type: boolean
        description: "Send mail"
        default: false
      from_addr:
        type: string
        description: "Default from address"
      to_addr:
        type: array
        description: "Default list of recipients"
      cc_addr:
        type: array
        description: "Default list of CC recipients"

      start:
        type: object
        properties:
          subject:
            type: string
            description: "Subject of the mail (jinja2 template)"
            default: "{{ config.analysis }} started"
          body:
            type: string
            description: "Body of the mail (jinja2 template)"
            secret: true
            default: |
              # {{ config.analysis }}

              Analysis has started for {{ samples.unique_ids|length }} sample(s).

              🔎 The following samples are being analyzed:
              |      ID     |  Run(s)  |
              | ----------- | -------- |
              {%- for id_, group in samples.split(by="id") %}
              | `{{ id_ }}` |
              {%- for sample in group -%}
              `{{ sample.run }}`{% if not loop.last %}, {% endif %}
              {%- endfor -%} |
              {%- endfor -%}
          attachments:
            type: array
            description: "List of files to attach"
            items:
              type: string
            default: []

      end:
        type: object
        properties:
          subject:
            type: string
            description: "Subject of the mail (jinja2 template)"
            default: "{{ config.analysis }} finished"
          body:
            type: string
            description: "Body of the mail (jinja2 template, supports markdown)"
            secret: true
            default: |
              # {{ config.analysis }}

              {{ samples.unique_ids|length }} sample(s) have been processed.

              {% if samples.failed -%}
              ❗️ Analysis failed for the following samples:
              |      ID     |  Run(s)  |
              | ----------- | -------- |
              {%- for id_, group in samples.failed.split(by="id") %}
              | `{{ id_ }}` |
              {%- for sample in group -%}
              `{{ sample.run }}`{% if not loop.last %}, {% else %} | {% endif %}
              {%- endfor -%}
              {%- endfor %}
              📋 See attached log for more information
              {% endif -%}

              {%- if samples.complete -%}
              ✅ Analysis completed successfully for the following samples:

              |      ID     |  Run(s)  |
              | ----------- | -------- |
              {%- for id_, group in samples.complete.split(by="id") %}
              | `{{ id_ }}` |
              {%- for sample in group -%}
              `{{ sample.run }}`{% if not loop.last %}, {% else %} | {% endif %}
              {%- endfor -%}
              {%- endfor %}

              {%- endif -%}
          attachments:
            type: array
            description: "List of files to attach"
            items:
              type: string
            default: []
          attachments_complete:
            type: array
            description: "List of files to attach if there are complete samples"
            items:
              type: string
            default: []
          attachments_failed:
            type: array
            description: "List of files to attach if there are failed samples"
            items:
              type: string
            default: ["{config.logdir}/{config.analysis}.{config.tag}.log"]

      smtp:
        type: object
        required:
          - host
        properties:
          host:
            type: string
            description: "SMTP host"
          port:
            type: integer
            description: "SMTP port"
            default: 25
          tls:
            type: boolean
            description: "Use TLS"
            default: false
          user:
            type: string
            description: "SMTP username"
          password:
            type: string
            description: "SMTP password"
            secret: true
