type: object
properties:
  nextflow:
    type: object
    properties:
      sge_queue:
        type: string
        description: SGE queue for nextflow manager
      sge_pe:
        type: string
        description: SGE parallel environment for nextflow manager
      sge_slots:
        type: integer
        description: SGE slots (threads) for nextflow manager
      config:
        type: path
        description: Nextflow config file
      profile:
        type: string
        description: Nextflow profile
      cluster_options:
        type: string
        description: Nextflow cluster options
      ansi_log:
        type: boolean
        default: false
        description: Enable ANSI log
    required:
      - sge_queue
      - sge_pe
      - sge_slots
      - profile
