type: object
properties:
  hcp:
    type: object
    properties:
      credentials:
        type: path
        description: IRIS credentials file
      parallel:
        type: integer
        description: Number of parallel HCP conenctions
        default: 4
    required:
      - credentials
      - fastq_temp
