properties:
  compress:
    type: object
    properties:
      enabled:
        description: Enable output compression
        type: boolean
        default: false
      threads:
        description: Threads for compression
        type: integer
        default: 4
      rules:
        description: Compression rules (list of mappings)
        type: array
        default: []
        items:
          type: mapping

